name: Build and Deploy on Push
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  Build-and-Deploy-on-Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run:
          vercel pull --yes --environment=production --token=${{
          secrets.VERCEL_TOKEN }}
      - uses: typst-community/setup-typst@v5
      - name: Build Resume
        run: |
          typst compile resume/main.typ --ignore-system-fonts --font-path="./resume/backend/fonts/" --input AAK_EMAIL="${{ secrets.AAK_EMAIL }}" --input AAK_PHONE="${{ secrets.AAK_PHONE }}"
          mv resume/main.pdf app/home/resume.pdf
      - name: Download JetBrains Mono Font and Author Photo
        run: curl -L
          "https://github.com/JetBrains/JetBrainsMono/raw/refs/heads/master/fonts/webfonts/JetBrainsMono%5Bwght%5D.woff2"
          -o "app/home/main.woff2"

          curl -L "https://github.com/alaminkouser.png" -o
          "app/home/alaminkouser.png"
      - name: Build DOCS
        run: |
          rm -rf app/home/docs
          deno run --config docs/deno.json preparePublicDirectory
          deno run --config docs/deno.json pagefind

          # MERMAID
          npm install -g @mermaid-js/mermaid-cli
          echo '{
            "args": ["--no-sandbox", "--disable-setuid-sandbox"]
          }' > puppeteer-config.json
          find ./docs/source -type f -name "*.md" -exec sh -c '
            for f; do
              mmdc -i "$f" -o "$f" -b transparent --puppeteerConfigFile puppeteer-config.json
            done
          ' sh {} +

          deno run --config docs/deno.json build

          mv docs/public app/home/docs
      - name: Move Sitemap
        run: mv app/home/docs/sitemap.xml app/home/sitemap.xml
      - name: Install Minifiers
        run: |
          npm install -g html-minifier-terser clean-css-cli terser
      - name: Minify HTML, CSS, JS
        run: |
          # HTML
          find ./app/home -type f -name "*.html" -exec sh -c '
            for f; do
              html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true -o "$f" "$f"
            done
          ' sh {} +
          # CSS
          find ./app/home -type f -name "*.css" -exec sh -c '
            for f; do
              cleancss -o "$f" "$f"
            done
          ' sh {} +
          # JS
          find ./app/home -type f -name "*.js" -exec sh -c '
            for f; do
              terser "$f" -o "$f" --compress --mangle --module
            done
          ' sh {} +
      - name: Deploy Project Artifacts to Vercel
        if: github.event_name != 'schedule'
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Skip Deploy on Schedule
        if: github.event_name == 'schedule'
        run: echo "Scheduled build completed. Skipping deployment."
